export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as BoxCallToAction } from './BoxCallToAction'
export { default as MainHero } from './MainHero'
export { default as BannerLogos } from './BannerLogos'
export { default as ServiceCards } from './ServiceCards'
export { default as BlogHero } from './BlogHero'
export { default as ServiceDetails } from './ServiceDetails'
export { default as NewsletterBox } from './NewsletterBox'
export { default as Testimonials } from './Testimonials'
export { default as FeaturedPosts } from './FeaturedPosts'
export { default as SidebarBlog } from './SidebarBlog'
export { default as BlogRoll } from './BlogRoll'
export { default as Hero } from './Hero'
export { default as Contact } from './Contact'
export { default as BlogPostSidebar } from './BlogPostSidebar'

